services:
  - type: web
    name: datachemical-lab-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: ML_SERVICE_URL
        value: https://modeldeploy-1rrr.onrender.com
      - key: PORT
        value: 5002
    healthCheckPath: /health